[package]
name = "werkzeug-reloader-patch"
version = "0.0.5"
description = "A monkey-patch for the Werkzeug reloader for use with Node.Py"
license = "MIT"

[dependencies.python]
Werkzeug = ">=0.12.2"
